routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\PbfController;
// use Illuminate\Routing\Route;

// use Illuminate\Routing\Route;

Route::get('/', function () {
    return view('auth.login');
})->name('home');

// ROuting view
Route::view('/blank', 'blank');

Route::middleware(['auth', 'checkRole:system,admin,apoteker,rawatinap,ruangoperasi'])->group(function () {
    Route::get('/dashboard', 'HomeController@index')->name('home');
    Route::get('dashboard/dataobat', 'DashboardController@dataObat')->name('dashboard.obat');
    // Route::get('dashboard/dataobat', 'DashboardController@dataObat')->name('dashboard.obat');
    Route::get('antrianobat', 'RequestController@antrianObat')->name('requestObat.admin');
    Route::post('updateantrianobat', 'RequestController@updateAdmin')->name('requestObat.updateadmin');
    // Route::get('pbfList', 'PbfController@pbfList')->name('pbf.listPbf');
});

Route::middleware(['auth', 'checkRole:system,admin'])->group(function () {
    Route::post('kategori/hapusdata/{id}', 'KategoriController@destroy');
    Route::resource('kategori', 'KategoriController');
    Route::post('dataobat/hapusdata/{id}', 'ObatController@destroy');
    Route::post('dataobat/fixdata', 'ObatController@fixdata');
    Route::resource('dataobat', 'ObatController');
    Route::post('dataobat/import', 'ObatController@importDataObat')->name('dataobat.importData');
    Route::post('dataobat/getData', 'ObatController@getData');
    Route::post('dataobat/pemasukan', 'ObatController@pemasukan')->name("dataobat.pemasukan");
    Route::post('dataobat/distribusi', 'ObatController@pengeluaran')->name("dataobat.distribusi");
    Route::post('obat/hapusdata/{id}', 'dataObatController@destroy');
    Route::resource('obat', 'dataObatController');
    Route::post('satuanobat/hapusdata/{id}', 'satuanObatController@destroy');
    Route::resource('satuanobat', 'satuanObatController');
    Route::post('pbf/hapusdata/{id}', 'PbfController@destroy');
    Route::resource('pbf', 'PbfController');
    Route::post('distribusi/hapusdata/{id}', 'DistribusiController@destroy');
    Route::post('distribusi/hapusdatadistribusi', 'DistribusiController@hapusdatadistribusi');
    Route::resource('distribusi', 'DistribusiController');
    Route::post('users/hapusdata/{id}', 'UsersController@destroy');
    Route::resource('users', 'UsersController');
    Route::get('cetak/antrianObatIndex', 'RequestController@cetakDistribusiIndex');
    Route::get('cetak/antrianObat', 'CetakController@cetakDistribusi');
    Route::post('request/batalkanProses', 'RequestController@batalkanProses');
});

Route::middleware(['auth', 'checkRole:system,apoteker,rawatinap,ruangoperasi'])->group(function () {
    Route::post('requestObat/hapusdata/{id}', 'RequestController@destroy');
    Route::resource('requestObat', 'RequestController');
    Route::get('apoteker/listDistribusi', 'ApotekersController@listDistribusi')->name('apoteker.listDistribusi');
    Route::post('apoteker/list', 'ApotekersController@listData')->name('apoteker.list');
    Route::post('apoteker/dataobat/{id}', 'ApotekersController@destroy');
    Route::resource('apoteker', 'ApotekersController');
    Route::post('getStokObat', 'RequestController@getStokObat');
    Route::group(['prefix' => 'stokopname'], function () {
        Route::get('', 'StokOpnameController@index');
        Route::get('toExcel', 'StokOpnameController@exportToExcel');
        Route::post('insertData', 'StokOpnameController@insertStokOpname');
        Route::post('getListHarga', 'StokOpnameController@getListHarga');
    });
    Route::group(['prefix' => 'groupData', 'middleware' => 'checkRole:ruangoperasi,system'], function () {
        Route::get('/', 'GroupController@index');
        Route::get('/add', 'GroupController@add');
        Route::get('/edit/{id}', 'GroupController@edit');
        Route::post('/getObat', 'GroupController@getObat');
        Route::post('/getData', 'GroupController@getData');
        Route::post('/addData', 'GroupController@addData');
        Route::post('/editData', 'GroupController@editData');
        Route::post('/deleteData', 'GroupController@deleteData');
    });
    Route::group(['prefix' => 'laporanpemakaianobat', 'middleware' => 'checkRole:ruangoperasi,system'], function () {
        Route::get('/', 'LaporanPemakaianController@index');
        Route::get('/add', 'LaporanPemakaianController@add');
        Route::get('/edit/{id}', 'LaporanPemakaianController@edit');
        Route::get('/detail/{id}', 'LaporanPemakaianController@detail');
        Route::get('/getObat', 'LaporanPemakaianController@getObat');
        Route::post('/getData', 'LaporanPemakaianController@getData');
        Route::post('/addData', 'LaporanPemakaianController@addData');
        Route::post('/editData', 'LaporanPemakaianController@editData');
        Route::post('/deleteData', 'LaporanPemakaianController@deleteData');
        Route::get('/cetakData', 'CetakController@cetakLaporanPemakaian');
        Route::post('/validasiData', 'LaporanPemakaianController@validasiData');
        Route::post('/batalkanValidasi', 'LaporanPemakaianController@batalkanValidasi');
    });
});

Auth::routes();

app/dataObat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;


class dataObat extends Model
{
    use SoftDeletes;

    protected $table = 'data_obat';
    protected $fillable = [
        'id', 'nama', 'pbf', 'kategori'
    ];
    protected $hidden = [
        'created_at', 'updated_at', 'deleted_at'
    ];

    protected $appends = ['harga_satuan_terakhir'];

    public function obat()
    {
        return $this->hasMany('App\DataPemasukan', 'obat_id');
    }

    public function stok()
    {
        return $this->hasOne('App\Stok', 'obat_id', 'id');
    }

    public function distribusi()
    {
        return $this->hasMany('App\Distribusi', 'obat_id', 'id');
    }

    public function requests()
    {
        return $this->hasMany('App\Requests', 'obat_id', 'id');
    }

    public function stokApotekers()
    {
        return $this->belongsTo('App\StokApotekersModel', 'obat_id', 'id');
    }

    public function distribusiApotekers()
    {
        return $this->hasMany('App\DistribusiApotekersModel', 'obat_id', 'id');
    }

    public function obatOne()
    {
        return $this->hasOne('App\DataPemasukan', 'obat_id')->latest();
    }

    public function getSatuanObatAttribute()
    {
        if (isset($this->obatOne->satuan_id)) {
            return $this->obatOne->satuan_id;
        } else {
            return 0;
        }
    }

    public function getKadaluwarsaObatAttribute()
    {
        if (isset($this->obatOne->tanggal_kadaluwarsa)) {
            return Carbon::parse($this->obatOne->tanggal_kadaluwarsa)->locale('id')->isoFormat('Do MMMM YYYY');
        } else {
            return 'Belum ditentukan';
        }
    }

    public function getNamaSatuanAttribute()
    {
        if ($this->satuan_obat != null) {
            return $this->belongsTo('App\SatuanJenis', 'satuan_obat', 'id')->first()->nama;
        } else {
            return 'Belum ditentukan';
        }
    }

    public function getHargaSatuanTerakhirAttribute()
    {
        if (isset($this->obatOne->harga_akhir_satuan)) {
            return $this->obatOne->harga_akhir_satuan;
        } else {
            return 0;
        }
    }

    public function groups()
    {
        return $this->belongsToMany('App\Group', 'group_obat', 'obat_id', 'group_id');
    }

    public function laporanOperasi()
    {
        return $this->belongsToMany('App\LaporanOperasi', 'laporanoperasi_obat', 'obat_id', 'laporan_id');
    }
}

app/Http/Controllers/dataObatController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\dataObat;
use App\Pbf;
use App\SatuanJenis;
use App\Kategori;
use Yajra\DataTables\Facades\DataTables;
use DB;

class dataObatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // dd($pbf);
        $pbf = Pbf::all();
        $satuanjenis = SatuanJenis::all();
        $kategori = Kategori::all();
        if ($request->ajax()) {
            // $dataObat = dataObat::orderBy('id', 'DESC')->with('stok')->get();
            $dataObat = DB::select("select data_obat.id, data_obat.pbf, data_obat.nama, data_obat.kategori, stok.stok from data_obat join stok on data_obat.id = stok.obat_id where data_obat.deleted_at is null");
            return DataTables::of($dataObat)
                ->addColumn(
                    'action',
                    function ($dataObat) {
                        $button = "<div class='btn-group'>";
                        $button .= "<a href='" . url('dataobat/' . $dataObat->id) . "' class='btn-sm btn btn-info'><i class='fa fa-search'></i></a>";
                        $button .= '<button type="button" class="btn btn-warning btn-sm btn-edit" id="' . $dataObat->id . '" data-nama="' . $dataObat->nama . '" data-pbf="' . $dataObat->pbf . '" data-kategori="' . $dataObat->kategori . '" data-toggle="tooltip" data-placement="bottom" title="Sunting data"><i class="fa fa-pencil-square-o"></i></button>';
                        $button .= '<button data-token="' . csrf_token() . '" data-id="' . $dataObat->id . '"  class="btn btn-danger btn-sm btn-delete" data-toggle="tooltip" data-placement="bottom" title="Hapus data"><i class="fa fa-trash-o"></i></button>';
                        $button .= "</div>";

                        return $button;
                    }
                )
                ->addColumn(
                    'ketersediaan',
                    function ($dataObat) {
                        return $dataObat->stok;
                    }
                )
                ->addIndexColumn()
                ->rawColumns(['action', 'ketersediaan'])
                ->make(true);
        }
        return view('pages.dataobat.index', compact('pbf', 'satuanjenis', 'kategori'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $check = dataObat::where('nama', '=', $request->nama)->count();
        if ($check == 0) {
            $dataObat = new dataObat();
            $dataObat->nama = $request->nama;
            $dataObat->pbf = $request->pbf;
            $dataObat->kategori = $request->kategori;
            $dataObat->save();
            $response = [
                'status' => true,
                'message' => 'Berhasil menambahkan data'
            ];
        } elseif ($check == 1) {
            $response = [
                'status' => false,
                'message' => 'Data sudah tersedia'
            ];
        } else {
            $response = [
                'status' => false,
                'message' => 'Gagal menambahkan data'
            ];
        }

        return response()->json($response);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $check = dataObat::where('nama', '=', $request->nama)->whereNotIn('id', [$id])->count();
        if ($check == 0) {
            $dataObat = dataObat::find($id);
            $dataObat->nama = $request->nama;
            $dataObat->pbf = $request->pbf;
            $dataObat->kategori = $request->kategori;
            $dataObat->save();
            $response = [
                'status' => true,
                'message' => 'Data berhasil diubah'
            ];
        } else {
            $response = [
                'status' => false,
                'message' => 'Data sudah tersedia'
            ];
        }
        return response()->json($response);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $dataObat = dataObat::find($id);
        $dataObat->delete();
        return response()->json(['success' => 'Data berhasil dihapus']);
    }
}

resources/views/pages/dataobat/index.blade.php
@extends('layouts.master')

@section('css')
<!-- code css here -->
{{-- Data Tables CSS --}}
<link rel="stylesheet" href="{{ asset('assets/vendors/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/vendors/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css') }}">
@endsection

@section('body')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="float-right">
                        <button type="button" class="btn btn-success btn-tambah">Tambah data</button>
                    </div>
                    <h2>List <strong>data obat</strong></h2>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="pbfTable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <td>No</td>
                                    <td>Nama</td>
                                    <td>Kategori</td>
                                    <td>Ketersediaan</td>
                                    <td>Aksi</td>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal" id="pbfModal" tabindex="-1" role="dialog" aria-labelledby="pbfModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-white" id="pbfModalLabel"><b>Tambah data obat</b></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" id="formPbf">
                    @csrf
                    <input type="hidden" id="type-action" name="type_action">
                    <input type="hidden" id="hidden_id" name="hidden_id">
                    <input type="hidden" id="_method" name="_method">
                    <div class="form-group">
                        <label for="nama">Nama Obat</label>
                        <input type="text" name="nama" id="nama" class="form-control" placeholder="Nama Obat" required>
                    </div>
                    <div class="form-group">
                        <label for="nama">PBF (Di data pemasukan tidak akan tampil)</label>
                        <select name="pbf" id="pbf" class="custom-select">
                            @foreach($pbf as $pbfData)
                            <option value="{{ $pbfData->nama }}">{{ $pbfData->nama }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="nama">Kategori</label>
                        <select name="kategori" id="kategori" class="custom-select">
                            @foreach($kategori as $kat)
                            <option value="{{ $kat->nama }}">{{ $kat->nama }}</option>
                            @endforeach
                        </select>
                    </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="button-action">Tambah PBF</button>
            </div>
            </form>
        </div>
    </div>
</div>
@endsection

@push('javascript')
<!-- javascript body here -->
<script>
    $(document).ready(function () {
        var table = $('#pbfTable').DataTable({
            paginate: true,
            info: true,
            sort: true,
            processing: true,
            serverSide: true,
            order: [1, 'ASC'],
            ajax: {
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: "{{ route('obat.index') }}",
                // method: 'POST',
            },
            columns: [{
                    data: 'DT_RowIndex',
                    orderable: false,
                    searchable: false,
                    class: 'text-center',
                    width: '10px'

                },
                {
                    data: 'nama',
                    name: 'nama'
                },
                {
                    data: 'kategori',
                },
                {
                    data: 'ketersediaan',
                    defaultContent: "Belum ada data"
                },
                {
                    data: 'action',
                    orderable: false,
                    searchable: false,
                    width: "20px"
                }
            ]
        });

        $('.btn-tambah').on('click', function (e) {
            e.preventDefault();
            $('.modal-header').removeClass('bg-warning').addClass('bg-success');
            $('.modal-title').text('Tambah data baru');
            $('#type-action').val('add');
            $('#_method').val('POST');
            $('#button-action').text('Tambah data').removeClass('btn-warning').addClass('btn-success');
            $('#formPbf')[0].reset();
            $('#pbfModal').modal('show');
            $('#nama').select();
            $('#nama').focus();
        });

        $(document).on('click', '.btn-edit', function () {
            var id = $(this).attr('id');
            var nama = $(this).data('nama');
            var pbf = $(this).data('pbf');
            var kategori = $(this).data('kategori');
            $('.modal-header').addClass('bg-warning');
            $('.modal-title').text('Sunting dataobat');
            $('#formPbf')[0].reset();
            $('#type-action').val('edit');
            $('#hidden_id').val(id);
            $('#nama').val(nama);
            $('#pbf').val(pbf);
            $('#kategori').val(kategori);
            $('#_method').val('PUT');
            $('#button-action').text('Update data').addClass('btn-warning').removeClass('btn-success');
            $('#pbfModal').modal('show');
            $('#nama').select();
            $('#nama').focus();
        })

        $('#formPbf').on('submit', function (e) {
            e.preventDefault();
            var method = '';
            var action = '';
            var id = $('#hidden_id').val();

            if ($('#type-action').val() == 'add') {
                action = '{{ route("obat.store") }}';
                method = 'POST';
                $.ajax({
                    url: action,
                    method: method,
                    data: $(this).serialize(),
                    dataType: 'json',
                    success: function (response) {
                        if (response.status == true) {
                            swal.fire({
                                title: response.message,
                                icon: 'success',
                                timer: 3000
                            });
                        } else {
                            swal.fire({
                                title: response.message,
                                icon: 'error',
                                timer: 3000
                            });
                        }
                        table.ajax.reload();
                        $('#pbfModal').modal('hide');
                        $('#formPbf').reset();
                    },
                    fail: function (response) {
                        swal.fire({
                            title: response.message,
                            icon: 'error',
                            timer: 3000
                        });
                        // location.reload();
                        $('#pbfModal').modal('hide');
                        $('#formPbf').reset();

                    },
                });
            }
            if ($('#type-action').val() == 'edit') {
                action = 'obat/' + id;
                method = 'POST';
                data = $(this).serialize();
                console.log(data);

                $.ajax({
                    url: action,
                    method: 'POST',
                    data: $(this).serialize(),
                    dataType: 'json',
                    success: function (response) {
                        if (response.status == true) {
                            swal.fire({
                                title: response.message,
                                icon: 'success',
                                timer: 3000
                            });
                        } else {
                            swal.fire({
                                title: response.message,
                                icon: 'error',
                                timer: 3000
                            });
                        }
                        table.ajax.reload();
                        $('#pbfModal').modal('hide');
                        $('#formPbf').reset();
                    },
                    fail: function () {
                        swal.fire({
                            title: 'Gagal menyunting data',
                            icon: 'error',
                            timer: 3000
                        });
                        table.ajax.reload();
                        $('#pbfModal').modal('hide');
                        $('#formPbf').reset();

                    },
                });
            }
        });

        $(document).on('click', '.btn-delete', function () {
            var id = $(this).data('id');
            var token = $(this).data('token');
            var pemasukan = $(this).data('pemasukan');

            swal.fire({
                title: 'Apakah anda yakin menghapus data?',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#e3342f',
                confirmButtonText: 'Hapus',
                cancelButtonText: 'Batal'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name=\"csrf-token\"]').attr(
                                'content')
                        },
                        url: '{{url("obat/hapusdata")}}' + '/' + id,
                        type: 'POST',
                        dataType: 'json',
                        data: {
                            'id': id,
                            'pemasukan': pemasukan,
                            '_method': 'POST',
                            '_token': token,
                        },
                        success: function () {
                            swal.fire({
                                title: 'Data berhasil dihapus',
                                icon: 'success',
                                timer: 3000,
                            });
                            table.ajax.reload();
                        },
                        fail: function () {
                            swal.fire({
                                title: 'Data gagal dihapus',
                                icon: 'error',
                                timer: 3000,
                            });
                            table.ajax.reload();
                        },
                    });
                }
            });
        });
    })

</script>
@endpush