routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\PbfController;
// use Illuminate\Routing\Route;

// use Illuminate\Routing\Route;

Route::get('/', function () {
    return view('auth.login');
})->name('home');

// ROuting view
Route::view('/blank', 'blank');

Route::middleware(['auth', 'checkRole:system,admin,apoteker,rawatinap,ruangoperasi'])->group(function () {
    Route::get('/dashboard', 'HomeController@index')->name('home');
    Route::get('dashboard/dataobat', 'DashboardController@dataObat')->name('dashboard.obat');
    // Route::get('dashboard/dataobat', 'DashboardController@dataObat')->name('dashboard.obat');
    Route::get('antrianobat', 'RequestController@antrianObat')->name('requestObat.admin');
    Route::post('updateantrianobat', 'RequestController@updateAdmin')->name('requestObat.updateadmin');
    // Route::get('pbfList', 'PbfController@pbfList')->name('pbf.listPbf');
});

Route::middleware(['auth', 'checkRole:system,admin'])->group(function () {
    Route::post('kategori/hapusdata/{id}', 'KategoriController@destroy');
    Route::resource('kategori', 'KategoriController');
    Route::post('dataobat/hapusdata/{id}', 'ObatController@destroy');
    Route::post('dataobat/fixdata', 'ObatController@fixdata');
    Route::resource('dataobat', 'ObatController');
    Route::post('dataobat/import', 'ObatController@importDataObat')->name('dataobat.importData');
    Route::post('dataobat/getData', 'ObatController@getData');
    Route::post('dataobat/pemasukan', 'ObatController@pemasukan')->name("dataobat.pemasukan");
    Route::post('dataobat/distribusi', 'ObatController@pengeluaran')->name("dataobat.distribusi");
    Route::post('obat/hapusdata/{id}', 'dataObatController@destroy');
    Route::resource('obat', 'dataObatController');
    Route::post('satuanobat/hapusdata/{id}', 'satuanObatController@destroy');
    Route::resource('satuanobat', 'satuanObatController');
    Route::post('pbf/hapusdata/{id}', 'PbfController@destroy');
    Route::resource('pbf', 'PbfController');
    Route::post('distribusi/hapusdata/{id}', 'DistribusiController@destroy');
    Route::post('distribusi/hapusdatadistribusi', 'DistribusiController@hapusdatadistribusi');
    Route::resource('distribusi', 'DistribusiController');
    Route::post('users/hapusdata/{id}', 'UsersController@destroy');
    Route::resource('users', 'UsersController');
    Route::get('cetak/antrianObatIndex', 'RequestController@cetakDistribusiIndex');
    Route::get('cetak/antrianObat', 'CetakController@cetakDistribusi');
    Route::post('request/batalkanProses', 'RequestController@batalkanProses');
});

Route::middleware(['auth', 'checkRole:system,apoteker,rawatinap,ruangoperasi'])->group(function () {
    Route::post('requestObat/hapusdata/{id}', 'RequestController@destroy');
    Route::resource('requestObat', 'RequestController');
    Route::get('apoteker/listDistribusi', 'ApotekersController@listDistribusi')->name('apoteker.listDistribusi');
    Route::post('apoteker/list', 'ApotekersController@listData')->name('apoteker.list');
    Route::post('apoteker/dataobat/{id}', 'ApotekersController@destroy');
    Route::resource('apoteker', 'ApotekersController');
    Route::post('getStokObat', 'RequestController@getStokObat');
    Route::group(['prefix' => 'stokopname'], function () {
        Route::get('', 'StokOpnameController@index');
        Route::get('toExcel', 'StokOpnameController@exportToExcel');
        Route::post('insertData', 'StokOpnameController@insertStokOpname');
        Route::post('getListHarga', 'StokOpnameController@getListHarga');
    });
    Route::group(['prefix' => 'groupData', 'middleware' => 'checkRole:ruangoperasi,system'], function () {
        Route::get('/', 'GroupController@index');
        Route::get('/add', 'GroupController@add');
        Route::get('/edit/{id}', 'GroupController@edit');
        Route::post('/getObat', 'GroupController@getObat');
        Route::post('/getData', 'GroupController@getData');
        Route::post('/addData', 'GroupController@addData');
        Route::post('/editData', 'GroupController@editData');
        Route::post('/deleteData', 'GroupController@deleteData');
    });
    Route::group(['prefix' => 'laporanpemakaianobat', 'middleware' => 'checkRole:ruangoperasi,system'], function () {
        Route::get('/', 'LaporanPemakaianController@index');
        Route::get('/add', 'LaporanPemakaianController@add');
        Route::get('/edit/{id}', 'LaporanPemakaianController@edit');
        Route::get('/detail/{id}', 'LaporanPemakaianController@detail');
        Route::get('/getObat', 'LaporanPemakaianController@getObat');
        Route::post('/getData', 'LaporanPemakaianController@getData');
        Route::post('/addData', 'LaporanPemakaianController@addData');
        Route::post('/editData', 'LaporanPemakaianController@editData');
        Route::post('/deleteData', 'LaporanPemakaianController@deleteData');
        Route::get('/cetakData', 'CetakController@cetakLaporanPemakaian');
        Route::post('/validasiData', 'LaporanPemakaianController@validasiData');
        Route::post('/batalkanValidasi', 'LaporanPemakaianController@batalkanValidasi');
    });
});

Auth::routes();

app/dataObat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;


class dataObat extends Model
{
    use SoftDeletes;

    protected $table = 'data_obat';
    protected $fillable = [
        'id', 'nama', 'pbf', 'kategori'
    ];
    protected $hidden = [
        'created_at', 'updated_at', 'deleted_at'
    ];

    protected $appends = ['harga_satuan_terakhir'];

    public function obat()
    {
        return $this->hasMany('App\DataPemasukan', 'obat_id');
    }

    public function stok()
    {
        return $this->hasOne('App\Stok', 'obat_id', 'id');
    }

    public function distribusi()
    {
        return $this->hasMany('App\Distribusi', 'obat_id', 'id');
    }

    public function requests()
    {
        return $this->hasMany('App\Requests', 'obat_id', 'id');
    }

    public function stokApotekers()
    {
        return $this->belongsTo('App\StokApotekersModel', 'obat_id', 'id');
    }

    public function distribusiApotekers()
    {
        return $this->hasMany('App\DistribusiApotekersModel', 'obat_id', 'id');
    }

    public function obatOne()
    {
        return $this->hasOne('App\DataPemasukan', 'obat_id')->latest();
    }

    public function getSatuanObatAttribute()
    {
        if (isset($this->obatOne->satuan_id)) {
            return $this->obatOne->satuan_id;
        } else {
            return 0;
        }
    }

    public function getKadaluwarsaObatAttribute()
    {
        if (isset($this->obatOne->tanggal_kadaluwarsa)) {
            return Carbon::parse($this->obatOne->tanggal_kadaluwarsa)->locale('id')->isoFormat('Do MMMM YYYY');
        } else {
            return 'Belum ditentukan';
        }
    }

    public function getNamaSatuanAttribute()
    {
        if ($this->satuan_obat != null) {
            return $this->belongsTo('App\SatuanJenis', 'satuan_obat', 'id')->first()->nama;
        } else {
            return 'Belum ditentukan';
        }
    }

    public function getHargaSatuanTerakhirAttribute()
    {
        if (isset($this->obatOne->harga_akhir_satuan)) {
            return $this->obatOne->harga_akhir_satuan;
        } else {
            return 0;
        }
    }

    public function groups()
    {
        return $this->belongsToMany('App\Group', 'group_obat', 'obat_id', 'group_id');
    }

    public function laporanOperasi()
    {
        return $this->belongsToMany('App\LaporanOperasi', 'laporanoperasi_obat', 'obat_id', 'laporan_id');
    }
}

resources/views/print/laporan_distribusi_pdf.blade.php
<style>
    table td {
        padding: 2px 4px;
        vertical-align: middle;
    }
</style>
<page backbottom="7mm" backtop="7mm">
    <page_footer>
        <table>
            <tr>
                <td>
                    <p>Dicetak tanggal: {{ $data->printDate }}, Oleh: {{ $data->printedBy }}</p>
                </td>
                <td style="width: 630px;"></td>
                <td>
                    <p>Halaman [[page_cu]] Dari [[page_nb]]</p>
                </td>
            </tr>
        </table>
    </page_footer>
    <table cellpadding="0" cellspacing="0" style=" margin-top: 5px;" width="100%">
        <tr>
            <td style="text-align: center; width: 734px; font-size: 18px; font-weight: 500;">
                Data Persetujuan Gudang
            </td>
        </tr>
        <tr>
            <td style="padding: 25px 0px 0px 0px; font-size: 14px; font-weight: 500;">
                Tanggal Konfirmasi Gudang : {{ $data->tanggalkonfirmasi }}
            </td>
        </tr>
    </table>
    <table cellpadding="0" cellspacing="0" style=" margin-top: 3em;">
        <tr>
            <td style="text-align: center; vertical-align: middle; border: 1px solid black; width:20px; background: #ddd;">
                No </td>
            <td style="text-align: center; vertical-align: middle; border: 1px solid black; width:250px; background: #ddd;">
                Nama Obat </td>
            <td style="text-align: center; vertical-align: middle; border: 1px solid black; width:114px; background: #ddd;">
                Satuan</td>
            <td style="text-align: center; vertical-align: middle; border: 1px solid black; width:200px; background: #ddd;">
                Kadaluwarsa </td>
            <td style="text-align: center; vertical-align: middle; border: 1px solid black; width:70px; background: #ddd;">
                Jumlah </td>
        </tr>
        @php
        $total = 0;
        @endphp
        @foreach($data as $detail)
        <tr>
            <td style="text-align: center; vertical-align: middle; border: 1px solid black;">
                {{$loop->iteration}} </td>
            <td style="text-align: left; vertical-align: middle; border: 1px solid black;">
                {{ $detail->nama_obat }}
            </td>
            <td style="text-align: center; vertical-align: middle; border: 1px solid black;">
                {{ $detail->nama_satuan ?? 'Belum ditentukan' }} </td>
            <td style="text-align: center; vertical-align: middle; border: 1px solid black;">
                {{ $detail->dataObat->kadaluwarsa_obat }}
            </td>
            <td style="text-align: right; vertical-align: middle; border: 1px solid black;">
                {{ number_format($detail->total) }} </td>
        </tr>
        @php
        $total += $detail->total;
        @endphp
        @endforeach
        <tr>
            <td colspan="4" style="font-weight: bold; font-size: 16px; text-align: center; border: 1px solid black;">
                Total</td>
            <td style="font-weight: bold; font-size: 16px; text-align: right; border: 1px solid black;">
                {{ number_format($total) }}</td>
        </tr>

    </table>
</page>