routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\PbfController;
// use Illuminate\Routing\Route;

// use Illuminate\Routing\Route;

Route::get('/', function () {
    return view('auth.login');
})->name('home');

// ROuting view
Route::view('/blank', 'blank');

Route::middleware(['auth', 'checkRole:system,admin,apoteker,rawatinap,ruangoperasi'])->group(function () {
    Route::get('/dashboard', 'HomeController@index')->name('home');
    Route::get('dashboard/dataobat', 'DashboardController@dataObat')->name('dashboard.obat');
    // Route::get('dashboard/dataobat', 'DashboardController@dataObat')->name('dashboard.obat');
    Route::get('antrianobat', 'RequestController@antrianObat')->name('requestObat.admin');
    Route::post('updateantrianobat', 'RequestController@updateAdmin')->name('requestObat.updateadmin');
    // Route::get('pbfList', 'PbfController@pbfList')->name('pbf.listPbf');
});

Route::middleware(['auth', 'checkRole:system,admin'])->group(function () {
    Route::post('kategori/hapusdata/{id}', 'KategoriController@destroy');
    Route::resource('kategori', 'KategoriController');
    Route::post('dataobat/hapusdata/{id}', 'ObatController@destroy');
    Route::post('dataobat/fixdata', 'ObatController@fixdata');
    Route::resource('dataobat', 'ObatController');
    Route::post('dataobat/import', 'ObatController@importDataObat')->name('dataobat.importData');
    Route::post('dataobat/getData', 'ObatController@getData');
    Route::post('dataobat/pemasukan', 'ObatController@pemasukan')->name("dataobat.pemasukan");
    Route::post('dataobat/distribusi', 'ObatController@pengeluaran')->name("dataobat.distribusi");
    Route::post('obat/hapusdata/{id}', 'dataObatController@destroy');
    Route::resource('obat', 'dataObatController');
    Route::post('satuanobat/hapusdata/{id}', 'satuanObatController@destroy');
    Route::resource('satuanobat', 'satuanObatController');
    Route::post('pbf/hapusdata/{id}', 'PbfController@destroy');
    Route::resource('pbf', 'PbfController');
    Route::post('distribusi/hapusdata/{id}', 'DistribusiController@destroy');
    Route::post('distribusi/hapusdatadistribusi', 'DistribusiController@hapusdatadistribusi');
    Route::resource('distribusi', 'DistribusiController');
    Route::post('users/hapusdata/{id}', 'UsersController@destroy');
    Route::resource('users', 'UsersController');
    Route::get('cetak/antrianObatIndex', 'RequestController@cetakDistribusiIndex');
    Route::get('cetak/antrianObat', 'CetakController@cetakDistribusi');
    Route::post('request/batalkanProses', 'RequestController@batalkanProses');
});

Route::middleware(['auth', 'checkRole:system,apoteker,rawatinap,ruangoperasi'])->group(function () {
    Route::post('requestObat/hapusdata/{id}', 'RequestController@destroy');
    Route::resource('requestObat', 'RequestController');
    Route::get('apoteker/listDistribusi', 'ApotekersController@listDistribusi')->name('apoteker.listDistribusi');
    Route::post('apoteker/list', 'ApotekersController@listData')->name('apoteker.list');
    Route::post('apoteker/dataobat/{id}', 'ApotekersController@destroy');
    Route::resource('apoteker', 'ApotekersController');
    Route::post('getStokObat', 'RequestController@getStokObat');
    Route::group(['prefix' => 'stokopname'], function () {
        Route::get('', 'StokOpnameController@index');
        Route::get('toExcel', 'StokOpnameController@exportToExcel');
        Route::post('insertData', 'StokOpnameController@insertStokOpname');
        Route::post('getListHarga', 'StokOpnameController@getListHarga');
    });
    Route::group(['prefix' => 'groupData', 'middleware' => 'checkRole:ruangoperasi,system'], function () {
        Route::get('/', 'GroupController@index');
        Route::get('/add', 'GroupController@add');
        Route::get('/edit/{id}', 'GroupController@edit');
        Route::post('/getObat', 'GroupController@getObat');
        Route::post('/getData', 'GroupController@getData');
        Route::post('/addData', 'GroupController@addData');
        Route::post('/editData', 'GroupController@editData');
        Route::post('/deleteData', 'GroupController@deleteData');
    });
    Route::group(['prefix' => 'laporanpemakaianobat', 'middleware' => 'checkRole:ruangoperasi,system'], function () {
        Route::get('/', 'LaporanPemakaianController@index');
        Route::get('/add', 'LaporanPemakaianController@add');
        Route::get('/edit/{id}', 'LaporanPemakaianController@edit');
        Route::get('/detail/{id}', 'LaporanPemakaianController@detail');
        Route::get('/getObat', 'LaporanPemakaianController@getObat');
        Route::post('/getData', 'LaporanPemakaianController@getData');
        Route::post('/addData', 'LaporanPemakaianController@addData');
        Route::post('/editData', 'LaporanPemakaianController@editData');
        Route::post('/deleteData', 'LaporanPemakaianController@deleteData');
        Route::get('/cetakData', 'CetakController@cetakLaporanPemakaian');
        Route::post('/validasiData', 'LaporanPemakaianController@validasiData');
        Route::post('/batalkanValidasi', 'LaporanPemakaianController@batalkanValidasi');
    });
});

Auth::routes();

app/Kategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Kategori extends Model
{
    use SoftDeletes;
    protected $connection = 'mysql';
    protected $table = 'kategori';

    protected $fillable = [
        'id',
        'nama',
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Kategori;
use Yajra\DataTables\Facades\DataTables;

class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // dd($pbf);
        if ($request->ajax()) {
            $kategori = Kategori::get();
            return DataTables::of($kategori)
                ->addColumn('action', function ($kategori) {
                    $button = "<div class='btn-group'>";
                    $button .= '<button type="button" class="btn btn-warning btn-sm btn-edit" id="' . $kategori->id . '" data-nama="' . $kategori->nama . '" data-toggle="tooltip" data-placement="bottom" title="Sunting data"><i class="fa fa-pencil-square-o"></i></button>';
                    $button .= '<button data-token="' . csrf_token() . '" data-id="' . $kategori->id . '"  class="btn btn-danger btn-sm btn-delete" data-toggle="tooltip" data-placement="bottom" title="Hapus data"><i class="fa fa-trash"></i></button></div>';

                    return $button;
                })
                ->addIndexColumn()
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('pages.kategori.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $check = Kategori::where('nama', '=', $request->nama)->count();
        if ($check == 0) {
            $kategori = new Kategori();
            $kategori->nama = $request->nama;
            $kategori->save();
            $response = [
                'status' => true,
                'message' => 'Berhasil menambahkan data'
            ];
        } elseif ($check == 1) {
            $response = [
                'status' => false,
                'message' => 'Data sudah tersedia'
            ];
        } else {
            $response = [
                'status' => false,
                'message' => 'Gagal menambahkan data'
            ];
        }

        return response()->json($response);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $check = Kategori::where('nama', '=', $request->nama)->count();
        if ($check == 0) {
            $kategori = Kategori::find($id);

            if ($kategori->nama == $request->nama) {
                $response = [
                    'status' => false,
                    'message' => 'Data sudah tersedia'
                ];
            } elseif ($kategori->nama != $request->nama) {
                $kategori->nama = $request->nama;
                $kategori->save();
                $response = [
                    'status' => true,
                    'message' => 'Data berhasil diubah'
                ];
            } else {
                $response = [
                    'status' => false,
                    'message' => 'Data gagal diubah'
                ];
            }
        } else {
            $response = [
                'status' => false,
                'message' => 'Data sudah tersedia'
            ];
        }
        return response()->json($response);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kategori = Kategori::find($id);
        $kategori->delete();
        return response()->json(['success' => 'Data berhasil dihapus']);
    }
}

resources/views/pages/kategori/index.blade.php
@extends('layouts.master')

@section('css')
<!-- code css here -->
<link rel="stylesheet" href="{{ asset('assets/vendors/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/vendors/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css') }}">
@endsection

@section('body')
<!-- code body here -->
<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-right">
                            <button type="button" class="btn btn-success btn-tambah">Tambah Data</button>
                        </div>
                        <h2 class="card-title">List <strong>Kategori Obat</strong></h2>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="pbfTable" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <td>No</td>
                                        <td>Kategori</td>
                                        <td>Aksi</td>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- .animated -->
</div>

<!-- Modal -->
<div class="modal" id="pbfModal" tabindex="-1" role="dialog" aria-labelledby="pbfModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-white" id="pbfModalLabel"><b>Tambah Data</b></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" id="formPbf">
                    @csrf
                    <input type="hidden" id="type-action" name="type_action">
                    <input type="hidden" id="hidden_id" name="hidden_id">
                    <input type="hidden" id="_method" name="_method">
                    <div class="form-group">
                        <label for="nama">Nama Kategori</label>
                        <input type="text" name="nama" id="nama" class="form-control" placeholder="Nama Kategori"
                            required>
                    </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="button-action">Tambah Data</button>
            </div>
            </form>
        </div>
    </div>
</div>
@endsection

@push('javascript')
<script>
    $(document).ready(function () {
        var table = $('#pbfTable').DataTable({
            paginate: true,
            info: true,
            sort: true,
            processing: true,
            serverSide: true,
            order: [1, 'ASC'],
            ajax: {
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: "{{ route('kategori.index') }}",
            },
            columns: [{
                    data: 'DT_RowIndex',
                    orderable: false,
                    searchable: false,
                    class: 'text-center',
                    width: "10px"

                },
                {
                    data: 'nama',
                    name: 'nama'
                },
                {
                    data: 'action',
                    orderable: false,
                    searchable: false,
                    class: 'text-center',
                    width: "20px"

                }
            ]
        });

        $('.btn-tambah').on('click', function (e) {
            e.preventDefault();
            $('.modal-header').removeClass('bg-warning').addClass('bg-success');
            $('.modal-title').text('Tambah kategori baru');
            $('#type-action').val('add');
            $('#_method').val('POST');
            $('#button-action').text('Tambah kategori').removeClass('btn-warning').addClass(
                'btn-success');
            $('#formPbf')[0].reset();
            $('#pbfModal').modal('show');
            $('#nama').select();
            $('#nama').focus();
        });

        $(document).on('click', '.btn-edit', function () {
            var id = $(this).attr('id');
            var nama = $(this).data('nama');
            $('.modal-header').addClass('bg-warning');
            $('.modal-title').text('Sunting data');
            $('#type-action').val('edit');
            $('#hidden_id').val(id);
            $('#nama').val(nama);
            $('#_method').val('PUT');
            $('#button-action').text('Update data').addClass('btn-warning').removeClass('btn-success');
            $('#pbfModal').modal('show');
            $('#nama').select();
            $('#nama').focus();
        })

        $('#formPbf').on('submit', function (e) {
            e.preventDefault();
            var method = '';
            var action = '';
            var id = $('#hidden_id').val();

            if ($('#type-action').val() == 'add') {
                action = '{{ route("kategori.store") }}';
                method = 'POST';
                $.ajax({
                    url: action,
                    method: method,
                    data: $(this).serialize(),
                    dataType: 'json',
                    success: function (response) {
                        if (response.status == true) {
                            swal.fire({
                                title: response.message,
                                icon: 'success',
                                // timer: 3000
                            });
                        } else {
                            swal.fire({
                                title: response.message,
                                icon: 'error',
                                // timer: 3000
                            });
                        }
                        table.ajax.reload();
                        $('#pbfModal').modal('hide');
                        $('#formPbf').reset();
                    },
                    fail: function (response) {
                        swal.fire({
                            title: response.message,
                            icon: 'error',
                            // timer: 3000
                        });
                        // location.reload();
                        $('#pbfModal').modal('hide');
                        $('#formPbf').reset();

                    },
                });
            }
            if ($('#type-action').val() == 'edit') {
                action = 'kategori/' + id;
                method = 'POST';
                data = $(this).serialize();
                console.log(data);

                $.ajax({
                    url: action,
                    method: 'POST',
                    data: $(this).serialize(),
                    dataType: 'json',
                    success: function (response) {
                        if (response.status == true) {
                            swal.fire({
                                title: response.message,
                                icon: 'success',
                                // timer: 3000
                            });
                        } else {
                            swal.fire({
                                title: response.message,
                                icon: 'error',
                                // timer: 3000
                            });
                        }
                        table.ajax.reload();
                        $('#pbfModal').modal('hide');
                        $('#formPbf').reset();
                    },
                    fail: function () {
                        swal.fire({
                            title: 'Gagal menyunting data',
                            icon: 'error',
                            timer: 3000
                        });
                        table.ajax.reload();
                        $('#pbfModal').modal('hide');
                        $('#formPbf').reset();

                    },
                });
            }
        });

        $(document).on('click', '.btn-delete', function () {
            var id = $(this).data('id');
            var token = $(this).data('token');

            swal.fire({
                title: 'Apakah anda yakin menghapus data?',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#e3342f',
                confirmButtonText: 'Hapus',
                cancelButtonText: 'Batal'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name=\"csrf-token\"]').attr(
                                'content')
                        },
                        url: '{{url("kategori/hapusdata")}}' + '/' + id,
                        type: 'POST',
                        dataType: 'json',
                        data: {
                            'id': id,
                            '_method': 'POST',
                            '_token': token,
                        },
                        success: function () {
                            swal.fire({
                                title: 'Data berhasil dihapus',
                                icon: 'success',
                                timer: 3000,
                            });
                            table.ajax.reload();
                        },
                        fail: function () {
                            swal.fire({
                                title: 'Data gagal dihapus',
                                icon: 'error',
                                timer: 3000,
                            });
                            table.ajax.reload();
                        },
                    });
                }
            });
        });
    })

</script>
@endpush